# Build an nginx image from alpine base image.
FROM nginx:1.15.7-alpine

# Expose 80 and 443.
EXPOSE 80 443

# Add new configuration.
ADD conf/nginx.conf /etc/nginx/
ADD conf/webapp.conf /etc/nginx/conf.d/
RUN rm /etc/nginx/conf.d/default.conf